#!/bin/bash

#if ! [ -x "$(command -v brew)" ]; then
#  echo 'Error: this script is intended for Mac, not linux.' >&2
#  exit 1
#fi
#

# --- Finding Framework python
FRAMEWORK_PYTHON_ROOT="/Library/Frameworks/Python.framework/Versions"
echo $FRAMEWORK_PYTHON_ROOT
FRAMEWORK_FOUND=1
if [ ! -d $FRAMEWORK_PYTHON_ROOT ]; then
    #echo "Framework not found in /Library/. Trying in /System"
    FRAMEWORK_PYTHON_ROOT="/System/Library/Frameworks/Python.framework/Versions"
    echo $FRAMEWORK_PYTHON_ROOT
    if [ ! -d $FRAMEWORK_PYTHON_ROOT ]; then
        #echo "Framework not found in /System. Trying in brew"
        PYSUBVER="$(python --version 2>&1 | cut -d ' ' -f2)"  # e.g., 2.7.10
        FRAMEWORK_PYTHON_ROOT="$(brew --prefix)/Cellar/python/$PYSUBVER/Frameworks/Python.framework/Versions"
	if [ ! -d $FRAMEWORK_PYTHON_ROOT ]; then
            FRAMEWORK_FOUND=0
        fi
    fi
fi


# --- Python exe - TODO, try python3 first
if [ "$FRAMEWORK_FOUND" == "1" ]; then
    PYVER=2.7
    FRAMEWORK_PYTHON="$FRAMEWORK_PYTHON_ROOT/$PYVER/bin/python$PYVER"
else
    # Try /usr/bin/python
    echo "[FAIL] Cannot find a system python installation"
    echo "       Find the path to your system python."
    echo "       Use the system python to launch pyDatView.py"
fi

if [ ! -f $FRAMEWORK_PYTHON ]; then
    echo "[FAIL] Framework python exe not found: $FRAMEWORK_PYTHON"
fi
echo "[INFO] Using: $FRAMEWORK_PYTHON"


# --- Setting up PYTHONHOME
if [ -z "$VIRTUAL_ENV" ] ; then
    echo "[WARN] You are not in a virtualenv. Thingsmight not work" 
    # find the root of the virtualenv, it should be the parent of the dir this script is in
    ENV_FROM_DIR=`dirname "$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"`
    ENV_FROM_PY=`$FRAMEWORK_PYTHON -c "import os; print os.path.abspath(os.path.join(os.path.dirname(\"$0\"), '..'))"`
    echo "ENV from python:       $ENV_FROM_PY"
    echo "ENV from dir:          $ENV_FROM_DIR"
    export PYTHONHOME=$ENV_FROM_PY
else
    VENV_SITE_PACKAGES="$VIRTUAL_ENV/lib/python$PYVER/site-packages"
    # Ensure wx.pth is set up in the virtualenv
    #cp "/Library/Python/$PYVER/site-packages/wxredirect.pth" "$VENV_SITE_PACKAGES/wx.pth"
    # Use the Framework Python to run the app
    export PYTHONHOME=$VIRTUAL_ENV
fi

# --- Launching python
exec $FRAMEWORK_PYTHON "$@"

