#----------------------------------------------------------------------
# This file was generated by png2pyem.py
#
from wx.lib.embeddedimage import PyEmbeddedImage

back = PyEmbeddedImage(
    b'iVBORw0KGgoAAAANSUhEUgAAABQAAAAUCAYAAACNiR0NAAAABHNCSVQICAgIfAhkiAAAAAlw'
    b'SFlzAAADEwAAAxMBPWaDxwAAABl0RVh0U29mdHdhcmUAd3d3Lmlua3NjYXBlLm9yZ5vuPBoA'
    b'AADPSURBVDiN3dOxSoJRGAbgx1wEESTRsTnKpSvoHprEa/ACugPRNbqCLkMcgrYkHVwcAjfR'
    b'1VHBBg3k+Pebnp+GXviG8w0P7zlw+C+5QQ9d5GOxW8yx2c1zDFYPsA0+s8RWeDgHu8YswNZo'
    b'/jmWC8519FEL9hO8pjhveAmXV1gEzX47a5TgYg+8R/XonZKTRzFclvBxZsMlChy+YcX2R9wF'
    b'+zGeUhoOdmUSU8Z7QotuCng0P6GdGLSCYQL6mDU6jQG/0dEe2IoF4RJtNLLATsoXBtpZc42g'
    b'ptUAAAAASUVORK5CYII=')

#----------------------------------------------------------------------
chart = PyEmbeddedImage(
    b'iVBORw0KGgoAAAANSUhEUgAAABQAAAAUCAYAAACNiR0NAAAABHNCSVQICAgIfAhkiAAAAAlw'
    b'SFlzAAADEwAAAxMBPWaDxwAAABl0RVh0U29mdHdhcmUAd3d3Lmlua3NjYXBlLm9yZ5vuPBoA'
    b'AAEzSURBVDiNrdQ7LwRRFADgb2XjEQ0RGgqFRqVReBYKBYWIqFQSnSglfoXST1BoJKIRj0oi'
    b'oZGIV6HyA8hSCckq5pBrrdfYk0xmzp2bb865d3ILmMCS2sRhEYOBFmoAdhWT5A7bOaG+uKTg'
    b'LeZzgqtvYF1OII0ZLIol+y84hXXUo/xfcBIbgb07ecFxbKIB91FlbnAUW1FZCSO4yQsOYweN'
    b'gQ3hOp3wF3AQu2jCQ+BXlZOqgd1YqBgbwH5gpcgvq321WJH34Agt6MUy+rGXVPapza/Adhyj'
    b'FS+yA6MNs2j2TZtppC13BvaEk3g3F9ijbDcvvsNSsBz3J9nfPyZrsxzYKM5/wlKwENh0QM/x'
    b'vBbY2W8wPq5hKSobS8aeZW3P/eCMVAM7sPLbSr6KIk5lm1CLE/vgFRE4ODkTvkH/AAAAAElF'
    b'TkSuQmCC')

#----------------------------------------------------------------------
filesave = PyEmbeddedImage(
    b'iVBORw0KGgoAAAANSUhEUgAAABQAAAAUCAYAAACNiR0NAAAABHNCSVQICAgIfAhkiAAAAAlw'
    b'SFlzAAADEwAAAxMBPWaDxwAAABl0RVh0U29mdHdhcmUAd3d3Lmlua3NjYXBlLm9yZ5vuPBoA'
    b'AAEkSURBVDiNzdQ/LwRBGMfxD/EnEiGIUInk1BrJtSKnpvMSvAidSqtXSq4WrUI0Gh2iOiLX'
    b'ECIXcRKRy1HsrGw2u3ZxhV8y2WeeeZ7v7PNkZvjv6kvYO6iUzDvHLtp5wGk84ASjWErExH5Y'
    b'Dt9hNFHDY9aOs/jACjaDHY96Iq6OQ8zhGlch90v9hcVlqxk2H8ZxEvpbYAytYQR7sXOgRGIF'
    b'q8FewH1i7RZb2Bf1vp0FvMQ7hsK8iqPE+nYq/k5UaS7wFOOiUtLq4CW7kEh5Jb+F8WPlAasY'
    b'K8h9xlkZ4DoOSv7QmtRtyQLO4BWLBbAL0flrFAGhi5sCYDfL+ZeDnameA+PXZgJPolswiEnR'
    b'LfhO8yGnI+rlFFpxD1vYUP49TKsRGL3XJzFBN0fw/0UoAAAAAElFTkSuQmCC')

#----------------------------------------------------------------------
forward = PyEmbeddedImage(
    b'iVBORw0KGgoAAAANSUhEUgAAABQAAAAUCAYAAACNiR0NAAAABHNCSVQICAgIfAhkiAAAAAlw'
    b'SFlzAAADEwAAAxMBPWaDxwAAABl0RVh0U29mdHdhcmUAd3d3Lmlua3NjYXBlLm9yZ5vuPBoA'
    b'AADHSURBVDiN1dI9SgNBGAbgJ1rFwiJKOmtBsUppEYkXCNqkyhG8gJ2NRWovk1PEwlbS7oJd'
    b'KhG02FlYJ1nZ3UzjCx8zDMPDNz/89xxigSUuUoAv+A6V4XJf8L0CJkGn+EyN3u1Ac1ztg943'
    b'RXuV+RzXf6BjnEdrOSZ4izcf4yvqoGllOCuhgzAeKf5clwxxEy/2senY4SqcEL/vcBSqLg+2'
    b'v8srbvHR+DwhTzWdnbaFkmOPNdhJFwzWKTGKh0iGlZnhGYMUWOv8AGO1V3vHZtKVAAAAAElF'
    b'TkSuQmCC')

#----------------------------------------------------------------------
hand = PyEmbeddedImage(
    b'iVBORw0KGgoAAAANSUhEUgAAABQAAAAUCAYAAACNiR0NAAAABHNCSVQICAgIfAhkiAAAAAlw'
    b'SFlzAAABuwAAAbsBOuzj4gAAABl0RVh0U29mdHdhcmUAd3d3Lmlua3NjYXBlLm9yZ5vuPBoA'
    b'AALHSURBVDiNrZM9bFNXFMd/594Xx9h+TmzAbRNAjRAU1WpFP+wyIFCmTqxIBWVgY6JDp25I'
    b'rEiVSoXaFZFKZWeshEBKIVBoYSFKVZDaNBAcJ3GcOPa77x4GhBPCc+jAf3v3/M/vno/74C1L'
    b'Ek9V5dJk7TOjwWERyioU8R5gHjEPFK6PfVH4838BL92p7zFOzyDywRsqud8Rd+FUtfSkJ3B8'
    b'cuGgqn4LZLZurKuGsf7cic93PHwNePnm/C6MnEfJbs6a+GdqeLa1mv94sDS7rzS8uDGmyjKd'
    b'+JuxIztnAUw3gHydBAN43GqWGoHNPWouFTbHRAglbU6//DYA47drVREOJDblPf3b0gSpALE9'
    b'Glf59OfJ+XIX6L052sMKQFgMyeSyGEl+FABxLEe6QEHLWwEz+QzpTD/WGO1pMv4jgOCsquHW'
    b'QuHlen6dfvD+jFsrptJ9DOwoEBZy2EzW6soiT6J24Zepu2HUiXBRjFHiQ0O7Z/a/t3tJxBQB'
    b'zNFrGJH1bc+7djZOpWzUl7KRsXZNrW0srdJaadE2NmgaSS8j6Yb36bl2O/v3Qm0AQL0GAMHo'
    b'qLjLt+rLQB5gJCzUZlqNwaATI7Ul3EKTRXwYeSQbRa3QpFY6fRhnjJhUv374zlD9xdioAwQA'
    b'qE4hUgGo7Nr7tAJPN45nfPr3T5wNgpz0rX65t/woaYQqPFxfirUTvWbtVcVFsbgoRl/8z4my'
    b'8FsXON28dw3V2WSix0URUceh3iVaFB5/VS3e7ALPjo46MeYiSmIJsfPq2h3Uk/BsNMIEP4iI'
    b'doEAJ6uFP7D8qLyaZKzVSmno3wPZcO7gu8NzG2OCOPXm+7FKfmr9bJPGb9eq3pszAgOJ/XUz'
    b'pWa8fnfiUPH+q5ck6MqEbmtL/ZgYOQyMbDAryF9KfCOV2371eFk6r92zZRXAT3f+y+T94PYW'
    b'LWRn8dmpEVnbyv8cYeYUXccLgBsAAAAASUVORK5CYII=')

#----------------------------------------------------------------------
home = PyEmbeddedImage(
    b'iVBORw0KGgoAAAANSUhEUgAAABQAAAAUCAYAAACNiR0NAAAABHNCSVQICAgIfAhkiAAAAAlw'
    b'SFlzAAADEwAAAxMBPWaDxwAAABl0RVh0U29mdHdhcmUAd3d3Lmlua3NjYXBlLm9yZ5vuPBoA'
    b'AAEDSURBVDiN7dOxSgNBEMbxn2JhZZPSwtLWRlvhGitbtbUQfARLfQSbYGlhIF3eIA8QLERE'
    b'sFMLSRGxi6CQWGQON+dJ7gQLwQ8GhtmZ/87OsPzrT2odD7gPH84wxjuW6sB2McRr2BA7OA/g'
    b'GI0qoDmcYIQ+tsL6SawycBEXkXyNDDe4C/8ygc0ELicFHWxjkBQPItZJYqvfwdbwGEmnOMRb'
    b'oZt8EUc4juc/YaMIy3wOfx/NElDRmpGbLytLgSvoYRPdCrDculHTC8YXNWrASpeyUEYt6Art'
    b'8PdMZl1ZZR22kvPWrA7n69xWRUXg6AeMqZriDF9wYPoZt4nfNvk9uZ6j5vf0AYnmbWwqHwK5'
    b'AAAAAElFTkSuQmCC')

#----------------------------------------------------------------------
matplotlib = PyEmbeddedImage(
    b'iVBORw0KGgoAAAANSUhEUgAAABQAAAAUCAYAAACNiR0NAAAABHNCSVQICAgIfAhkiAAAAAlw'
    b'SFlzAAADEwAAAxMBPWaDxwAAABl0RVh0U29mdHdhcmUAd3d3Lmlua3NjYXBlLm9yZ5vuPBoA'
    b'AAOUSURBVDiNhZVdTFtlGMf/p6eTFhIDlcnQMkAx0sWhayXgTFiMEJlkF9CCmHQLF2qaVIfz'
    b'KyRrGVlcvNq4mVl03mA0YuhhcWIhnuNiWg9dDYyxIVbrSsYoiHbtYRuttJ7zeDPKV4v/u/fj'
    b'+eV9nud9/y+D7GLb2tperq6uNul0ugIiolgsJvn9/jGXyzUMQN4mdk16vV7rdDodgiAERMFN'
    b'4ZshWq94PE48zwccDsdxADnbwpqbmw2Dg4M+z4XP6aL9OVroUJP73EnKJEVRiOO4UbPZXJkV'
    b'Jopi8GLfWbrV8QCRDUQ2kPtE+wZQMpncMBZFMbgFqtfrtRzH+VYD+o82rAFfr0oHh+dn6cNP'
    b'nyfOfZoURUnPcxznKysr06SBXV1dJ2RZTm+ILC6Q+42niWygKauWbs7cICKir4dO0RUy0Mf9'
    b'bZRKpTak393dfRwAVADY+vr6V1UqFSbGfwIAPPTwLlTYP4M/tRuGvAR+9boBAHfhw1W+GJYX'
    b'eqFWq9MHYhgGdXV1hwGwrMViaers7HxrcTGMW8IBTI0PYz5C2Lf/IMI79FiZ4nF7RxGk3DyE'
    b'Ey4YH/kIFY/t3dKD4uLiwlAoNKaura01ajQaXPdzaHxGAuDBnWUvvvvkPDSPWvH3s+9iaWIE'
    b'v08oeLzUBuPeAxmbqtVqYTKZ9ql1Ot1OAGBSf6YXH8wjHKq6jMTKZVyCEaPRFcy6ZzCS+ySK'
    b'dNOoNu7JCC0oKChUExGtTigKEFpQ40ZkN0hTjiRTgv7fEkjkJ5E7/xfeOWbCU4byjLD7IlUs'
    b'FosAgL7yEPjoOTDGKTTYgpgofA2nr7LosB7DS+YG1FlbMHTmPUyPCllp0Wg0gpaWlqbl5eW1'
    b'S3Vf54cG6e69e0REdNLdQ73DZ2hSFGjglRL69mzPhnu4+iTb29ubAIAVBCGQ8X0RkSzLdHTk'
    b'TeoZ7iYiou/7eil4JIe+et9Cd5ak9D6e5wMAWBUAWRCELxVFyZjG5PQk2D0qSJAAAA1H3saV'
    b'civMSy78+EE9gtfGQETwer19AGQWAObm5n4uLS190WAwlGwGKoqCxC//oOjfXaiqqALDMHhi'
    b'fyO+uTSKgykRPyyo8cftpM9ut9uw3tLMZnOlKIrBbKlv1vzsDH1xqpM8Hs9Wc1gP5TjOt7ng'
    b'2Wq7rX2tU47T6XTwPB+Ix+NbQP9nsMw2YLa1tbWxpqbGlJ+frwMASZKifr9/fGBgYARZvoD/'
    b'ALbUv1CeVdYmAAAAAElFTkSuQmCC')

#----------------------------------------------------------------------
move = PyEmbeddedImage(
    b'iVBORw0KGgoAAAANSUhEUgAAABQAAAAUCAYAAACNiR0NAAAABHNCSVQICAgIfAhkiAAAAAlw'
    b'SFlzAAADEwAAAxMBPWaDxwAAABl0RVh0U29mdHdhcmUAd3d3Lmlua3NjYXBlLm9yZ5vuPBoA'
    b'AAEJSURBVDiNxdO/SgNBEMfxT4Ldeb1glSKFIPgC2pk3SJNasLJM5zPYChHyElZBLITE1krw'
    b'CQQrQUgRUhgL5+IS/yS5Czjwg2V+N9+d3dnjHyLHXSivCssCNAvdV4FmGCWwQqPw1o4jTH8A'
    b'TnFYtkvoJLDOso/rVXZaBsxxg+4a9d2omQ+qAGa4RgvNNYDNqBmk0G0Mfd3TBK+Jxok3XvAm'
    b'iTcMlrbvkyyrdi2OfYWT6PgZT8mxdrAf60e8JN4edmPdx2lh1HAZu/QW7umvZ9OLfD8asxXG'
    b'DGd4w4PV49bnXZ7jfdWijT3sOg7QSHKNyJX6IVp+n+ZxGWA6qFTzAWwCWglWRB0XoaWwDzjV'
    b'Yxxlw3WKAAAAAElFTkSuQmCC')

#----------------------------------------------------------------------
subplots = PyEmbeddedImage(
    b'iVBORw0KGgoAAAANSUhEUgAAABQAAAAUCAYAAACNiR0NAAAABHNCSVQICAgIfAhkiAAAAAlw'
    b'SFlzAAADEwAAAxMBPWaDxwAAABl0RVh0U29mdHdhcmUAd3d3Lmlua3NjYXBlLm9yZ5vuPBoA'
    b'AAEPSURBVDiN5dS9SgNREAXgz2QFRVAsxGCjiCA2voOVCDZaiGXAJ7Cw8w0sBXtLeztfwFqs'
    b'Ff8KEUKwUiSJhXfh5iYbNoogeGDYc2Znzix7d5Z/h5E+uQmsoxr0JR5+MqSOThSnwzRXwrUW'
    b'GWwkNWPJgKKoQRaamtgJfDni0E50EZpFN1ZwjosQ2yXM/g4O0QjxgrW0IH+HkzgqYTiF6Uhv'
    b'YjfwA7zmhhkWSxg2Ej0e9WW+gWPdn8pWWtBvUwahgoXA3/E0jOE+ZgO/x0mZibnhKFaj/Buu'
    b'I93Bku4DSXGFj1zEq9fBmd7V6pfrWb38CauYj6a1cZvoOV9/oiLcoZUfdQs3ScEeZgJ/xPMA'
    b's9/DJwnERTgPlO7HAAAAAElFTkSuQmCC')

#----------------------------------------------------------------------
zoom_to_rect = PyEmbeddedImage(
    b'iVBORw0KGgoAAAANSUhEUgAAABQAAAAUCAYAAACNiR0NAAAABHNCSVQICAgIfAhkiAAAAAlw'
    b'SFlzAAADEwAAAxMBPWaDxwAAABl0RVh0U29mdHdhcmUAd3d3Lmlua3NjYXBlLm9yZ5vuPBoA'
    b'AAFgSURBVDiNrdSxS5VRHMbxz1WTIB2FliQd2lwscckIcYlG3aQpmvwL/AfcHaTFRbQxGoKa'
    b'ItR0cknbokgQcgoiCS2vOdzzcn/dPO9rVx848B7O9zzn+R1+7+GSVStZ68Ud9OEA29hr55BB'
    b'PMMh/oRxgk1M/I/ZA3xvMWodJ5iTqa4zfI/iNa6l+UfMYxHruJLS1zCGI7zLJevETkgxj64z'
    b'uEnNq/iFWznDh8HsZa6cpJnAPs1BCwEaKTGjUc3XxO7moFcJOKxIV+hF4uvojgsd4VQhZZXq'
    b'Yf9fd10YFtGvYqjCrKZ5Lfv4eRY0GdKtVBhOB3YpB3XjUwBnM9w9zcav43bZyRP4HUw38ATj'
    b'mMIyjsP6NwxUVOORf//hsvHlPKbDeJMx+IzHWGsxvVlsLuu5ftzFdfzAe2xpPA49Gr07lthd'
    b'3E/mbasHqyHpc5p92I4ONN6At2n+4SLpojpwo5icAgxhck2Uf3zTAAAAAElFTkSuQmCC')

